### ISSUE TITLE
Error when running code

### ISSUE THREAD

**Issue by usmaann** [PrashantRanjan09/WordEmbeddings-Fasttext-Word2Vec#3]
hello , i get below mentioned error when i tried to train model with W2V, Fastttext 

![image](https://user-images.githubusercontent.com/38275359/51457102-2be85800-1da4-11e9-8c2e-1bf25d19e8bc.png)

please advise. thnx

**Comment by PrashantRanjan09** [comment]
@usmaann : The error suggests that you didn't specify the "option" parameter in the config file.
In config.json specify “option” as 0 – Word2vec, 1 – Gensim FastText, 2- Fasttext (FAIR), 3- ELMo.

This should solve your problem.

**Comment by usmaann** [comment]
Hello Prashant 
i tried to input my dataset in X Y form, when I run using any options I get below error.
![image](https://user-images.githubusercontent.com/38275359/51746080-130bd980-20f9-11e9-8a15-5f6f132abc6b.png)
t below error, pls advise how to fix
