### ISSUE TITLE
 Allocation of 1258291200 exceeds 10% of system memory. Killed

### ISSUE THREAD

**Issue by ghost** [PrashantRanjan09/WordEmbeddings-Fasttext-Word2Vec#4]
Hi,

I get the following error when I run the code. Any workaround for this?

2019-01-25 18:56:48.821520: W tensorflow/core/framework/allocator.cc:101] Allocation of 18454937600 exceeds 10% of system memory.
2019-01-25 18:56:48.821663: W tensorflow/core/framework/allocator.cc:101] Allocation of 1258291200 exceeds 10% of system memory.
Killed
.

I have already tried decreasing batch size but didn't help.

**Comment by PrashantRanjan09** [comment]
@BuggyLife Looking at the error I think it has to do something with your data and memory allocation. Whats the size of data you are using and other params like dimensions etc.

Have you tried running it on a GPU. Not sure, but it may resolve the problem if its due to memory allocation.

**Comment by SarangShaikh201** [comment]
I am also getting the same error as above. Can you please guide?

**Comment by SarangShaikh201** [comment]
I m using default config

**Comment by PrashantRanjan09** [comment]
@SarangShaikh201 @ghost: i think the problem is because of _batch size_ being set to a little higher value.
Try running the code with _batch size_ = 16 or smaller value. Worst case try running it _batch size_ = 1.
Should solve the error.
