### ISSUE TITLE
Elmo embeddings with different dataset

### ISSUE THREAD

**Issue by usmaann** [PrashantRanjan09/WordEmbeddings-Fasttext-Word2Vec#5]
Hello, i tried to run your code with my dataset, i am able to word2vec/fasttext gensim with my dataset but unable to understand how u r handling word vectors for Elmo. in below screenshot.

how to change these values in below elmo function ( in my case x_text, y is a X Y form )
(train_x,train_y,test_x,test_y,max_len)

please advise how to change 
![image](https://user-images.githubusercontent.com/38275359/51782004-5f94fa80-2175-11e9-938b-59f708f2370c.png)

**Comment by PrashantRanjan09** [comment]
@usmaann X = Your corpus
                    Y = Label (say you are doing classification)
then: 
      *embed_seq = layers.Lambda(ELMoEmbedding, output_shape=(1024,))(input_text)*
will take in the input text as mentioned in the script and the embed_seq (shown above) will get the embedding of the "input_text" in 1024 dimensions (as recommended In the paper)

I don't think you have to make any changes in your data, the script should automatically take care of that. Just feed the data in the specified format.
