### ISSUE TITLE
Elmo embeddings for urdu language corpus

### ISSUE THREAD

**Issue by samreenkazi** [PrashantRanjan09/WordEmbeddings-Fasttext-Word2Vec#6]
Do we have to change anything other then dataset to train elmo embedding in urdu language corpus?is it neccessary to use GPU to train model and any preprocessing of data required before training ?

**Comment by PrashantRanjan09** [comment]
@samreenkazi : Nope, Just use the training corpus in the required format.
GPU is not necessary however training time will be on a little higher side if you do it on CPU.
No preprocessing is required. All the pre processing scripts are already provided. Just you have to have the training files in the right format.
